# Generated by Django 4.0.1 on 2022-01-29 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15, verbose_name='Nome')),
                ('gos', models.CharField(max_length=15, verbose_name='GOS')),
                ('status', models.CharField(max_length=15, verbose_name='Status')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descricao')),
                ('data_inicio', models.CharField(max_length=15, verbose_name='Data Início')),
                ('prox_atualizacao', models.CharField(max_length=15, verbose_name='Proxima Atualizacao')),
                ('polo', models.CharField(max_length=30, verbose_name='Polo')),
                ('historico', models.CharField(max_length=300, verbose_name='Histórico')),
                ('estacao', models.CharField(max_length=6, verbose_name='Estação')),
                ('afeta', models.CharField(choices=[('y', 'Sim'), ('n', 'Não')], max_length=1, verbose_name='Afetação')),
            ],
        ),
    ]
